kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm run lint

- name: build
  image: alpine
  commands:
  - apk --no-cache add zip
  - sh build.sh

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: RELEASE_TOKEN
    files:
    - dist/*
    checksum:
    - sha256
  when:
    event: tag
node:
  os: linux