kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm run lint

- name: Up Version
  image: node:alpine
  commands:
  - apk --no-cache add zip bash git
  - git config user.email "automation@tosdr.org"
  - git config user.name "ToS;DR Automation"
  - npm version $DRONE_DEPLOY_TO --no-git-tag-version
  - cat src/manifest.json | sed '/"version":/ s/"version":[^,]*/"version":"'$(npm run env | grep npm_package_version | cut -d '=' -f 2)'"/' > src/manifest.json
  - git add . && git commit -m "Update manifest version"
  - git tag $(npm run env | grep npm_package_version | cut -d '=' -f 2) -a -m "Updated to $(npm run env | grep npm_package_version | cut -d '=' -f 2)"
  - sed -i 's/\r$//' build.sh
  when:
    event:
    - promote

- name: Push Tags
  image: appleboy/drone-git-push
  settings:
    branch: master
    remote: git@github.com:tosdr/browser-extensions.git
    force: false
    ssh_key:
        from_secret: SSH_KEY
    commit: true
    author_name: "ToS;DR Automation"
    author_email: "automation@tosdr.org"
    followtags: true
    commit_message: "Release"
  when:
    event:
    - promote    
    target:
    - patch
    - minor
    - major

- name: Build Extension
  image: node:alpine
  commands:
  - apk --no-cache add zip bash
  - bash build.sh
 
   
- name: Upload Artifacts
  image: plugins/s3
  settings:
    bucket: tosdr-artifacts
    source: ./**/*
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    exclude:
      - .git
      - node_modules
      - .vs
    target: /browser-extensions/builds/${DRONE_BUILD_NUMBER}
    endpoint: https://s3.eu-west-2.jbcdn.net

- name: Sign Release  
  image: plugins/gpgsign
  settings:
    key:
        from_secret: SIGN_KEY
    passphrase:
        from_secret: SIGN_KEY_PASS
    files:
      - dist/*
  when:
    event:
    - tag

- name: Publish GitHub Release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: RELEASE_TOKEN
    files:
    - dist/*
    checksum:
    - sha256
  when:
    event:
    - tag
